trigger:
- main

pool:
  name: self-hosted    # apne self-hosted agent pool ka naam

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- script: terraform init
  displayName: Terraform Init

- script: terraform validate
  displayName: Terraform Validate

- script: terraform plan
  displayName: Terraform Plan
